# Generated by Django 5.2.12 on 2026-03-26 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
        ('users', '0002_memberprofile_trainer_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDiaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('etiqueta_dia', models.CharField(choices=[('A', 'Day A'), ('B', 'Day B'), ('C', 'Day C'), ('D', 'Day D')], max_length=1)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'plantillas_dias_entrenamiento',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grupo_muscular', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=20)),
                ('series', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('rango_repeticiones', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,3}(-\\d{1,3})?$', 'Formato válido: 8 o 8-12')])),
                ('peso_sugerido_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descanso_segundos', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(600)])),
                ('notas_tecnicas', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='plans.plantilladiaentrenamiento')),
            ],
            options={
                'db_table': 'plantillas_ejercicios',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('objetivo', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general', 'General')], default='general', max_length=20)),
                ('nivel_adherencia_recomendado', models.CharField(choices=[('low', 'Baja adherencia'), ('medium', 'Adherencia media'), ('high', 'Alta adherencia')], default='medium', max_length=10)),
                ('dias_por_semana_sugeridos', models.PositiveIntegerField(default=3)),
                ('esta_activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_entrenamiento', to='users.trainerprofile')),
            ],
            options={
                'db_table': 'plantillas_entrenamiento',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='plantilladiaentrenamiento',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='plans.plantillaentrenamiento'),
        ),
    ]
