# Generated by Django 5.2.12 on 2026-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plantilladiaentrenamiento_plantillaejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillaentrenamiento',
            name='objetivo',
            field=models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('maintenance', 'Maintenance'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='goal',
            field=models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('maintenance', 'Maintenance'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
