# Generated by Django 5.2.12 on 2026-04-08 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plantillaentrenamiento_objetivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('timed', 'Timed')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='plans.gymmachine'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='plantillaejercicio',
            name='minutos_objetivo',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='plantillaejercicio',
            name='tipo_ejercicio',
            field=models.CharField(choices=[('strength', 'Strength'), ('timed', 'Timed')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='day_of_week',
            field=models.CharField(choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miercoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sabado'), ('sun', 'Domingo')], default='mon', max_length=3),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps_range',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,3}(-\\d{1,3})?$', 'Formato válido: 8 o 8-12')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='plantillaejercicio',
            name='rango_repeticiones',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,3}(-\\d{1,3})?$', 'Formato válido: 8 o 8-12')]),
        ),
        migrations.AlterField(
            model_name='plantillaejercicio',
            name='series',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
