# Generated by Django 5.2.12 on 2026-04-08 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plantillaentrenamiento_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('timed', 'Timed')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='plantillaejercicio',
            name='minutos_objetivo',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='plantillaejercicio',
            name='tipo_ejercicio',
            field=models.CharField(choices=[('strength', 'Strength'), ('timed', 'Timed')], default='strength', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps_range',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,3}(-\\d{1,3})?$', 'Formato válido: 8 o 8-12')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='plantillaejercicio',
            name='rango_repeticiones',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,3}(-\\d{1,3})?$', 'Formato válido: 8 o 8-12')]),
        ),
        migrations.AlterField(
            model_name='plantillaejercicio',
            name='series',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
