# Generated by Codex on 2026-07-16

from django.db import migrations, models


def sync_status_from_is_active(apps, schema_editor):
    TrainingPlan = apps.get_model('plans', 'TrainingPlan')
    TrainingPlan.objects.filter(is_active=True).update(status='active')
    TrainingPlan.objects.filter(is_active=False).update(status='finished')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_exercise_exercise_type_exercise_target_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Borrador'),
                    ('active', 'Activo'),
                    ('scheduled', 'Programado'),
                    ('finished', 'Finalizado'),
                    ('archived', 'Archivado'),
                ],
                default='active',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='level',
            field=models.CharField(
                choices=[
                    ('beginner', 'Principiante'),
                    ('intermediate', 'Intermedio'),
                    ('advanced', 'Avanzado'),
                    ('custom', 'Personalizado'),
                ],
                default='intermediate',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(sync_status_from_is_active, noop_reverse),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['member', 'status'], name='plans_train_member_status_idx'),
        ),
    ]
