# Generated by Django 5.1.15 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_catalogo_ciclo_y_plantillas_compartidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoejercicio',
            name='identificador_origen',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
