# Generated by Django 5.2.12 on 2026-03-28 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('classes', '0002_initial'),
        ('users', '0002_memberprofile_trainer_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'check_in_time'], name='attendance__member__1a4486_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['checked_in_by', 'check_in_time'], name='attendance__checked_e4ea86_idx'),
        ),
    ]
