# Generated by Django 5.2.12 on 2026-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_attendance__member__1a4486_idx_and_more'),
        ('plans', '0004_alter_plantillaentrenamiento_objetivo_and_more'),
        ('progress', '0002_initial'),
        ('users', '0003_memberprofile_users_membe_trainer_0c80c8_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['member', 'recorded_at'], name='progress_pr_member__776a98_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['member', 'is_completed', 'started_at'], name='progress_wo_member__ca3019_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['workout_day', 'started_at'], name='progress_wo_workout_ff7da3_idx'),
        ),
    ]
