# Generated by Django 5.2.12 on 2026-04-08 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_progresslog_progress_pr_member__776a98_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='minutes_completed',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
