# Generated by Django 5.0.7 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_exerciselog_minutes_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='estado',
            field=models.CharField(
                choices=[('realizado', 'Realizado'), ('omitido', 'Omitido')],
                default='realizado',
                max_length=12,
            ),
        ),
    ]
