# Generated by Django 5.2.12 on 2026-03-28 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
        ('users', '0002_memberprofile_trainer_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='inactivityalert',
            index=models.Index(fields=['member', 'resolved', 'created_at'], name='alerts_inac_member__ed9ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='alerts_noti_user_id_225150_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='alerts_noti_type_70443c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['dedupe_key'], name='alerts_noti_dedupe__cb05fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uniq_notification_dedupe_key'),
        ),
    ]
