# Generated by Django 5.1.15 on 2026-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_notification_dedupe_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('inactivity', 'Inactivity'), ('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('plan_assigned', 'Plan Assigned'), ('trainer_message', 'Trainer Message'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
