# Generated by Django 5.1.15 on 2026-07-15 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_alert_statuses(apps, schema_editor):
    InactivityAlert = apps.get_model('alerts', 'InactivityAlert')

    InactivityAlert.objects.filter(resolved=True).update(status='resolved')
    InactivityAlert.objects.filter(resolved=False).update(status='new')

    member_ids = (
        InactivityAlert.objects
        .filter(status__in=['new', 'in_follow_up'])
        .values_list('member_id', flat=True)
        .distinct()
    )
    for member_id in member_ids:
        open_alerts = list(
            InactivityAlert.objects
            .filter(member_id=member_id, status__in=['new', 'in_follow_up'])
            .order_by('-created_at', '-id')
        )
        for duplicate in open_alerts[1:]:
            duplicate.status = 'dismissed'
            duplicate.status_change_reason = 'Descartada automáticamente por migración: alerta abierta duplicada.'
            duplicate.save(update_fields=['status', 'status_change_reason'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_notification_type'),
        ('users', '0004_auditlog_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InactivityAlertContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call'), ('email', 'Email'), ('in_person', 'In person')], max_length=20)),
                ('result', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contacted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberJustifiedAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='inactivityalert',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inactivityalert',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_follow_up', 'In follow-up'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='inactivityalert',
            name='status_change_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inactivityalert',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inactivityalert',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inactivity_alert_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_alert_statuses, noop_reverse),
        migrations.AddIndex(
            model_name='inactivityalert',
            index=models.Index(fields=['member', 'status', 'created_at'], name='alerts_inac_member__ed8e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='inactivityalert',
            index=models.Index(fields=['status', 'created_at'], name='alerts_inac_status_256864_idx'),
        ),
        migrations.AddIndex(
            model_name='inactivityalert',
            index=models.Index(fields=['last_checkin_date'], name='alerts_inac_last_ch_a44367_idx'),
        ),
        migrations.AddConstraint(
            model_name='inactivityalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'in_follow_up'])), fields=('member',), name='uniq_open_inactivity_alert_per_member'),
        ),
        migrations.AddField(
            model_name='inactivityalertcontact',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='alerts.inactivityalert'),
        ),
        migrations.AddField(
            model_name='inactivityalertcontact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_contacts', to='users.memberprofile'),
        ),
        migrations.AddField(
            model_name='inactivityalertcontact',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_contacts', to='users.trainerprofile'),
        ),
        migrations.AddField(
            model_name='memberjustifiedabsence',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justified_absences', to='users.memberprofile'),
        ),
        migrations.AddField(
            model_name='memberjustifiedabsence',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justified_absences', to='users.trainerprofile'),
        ),
        migrations.AddIndex(
            model_name='inactivityalertcontact',
            index=models.Index(fields=['member', 'contacted_at'], name='alerts_inac_member__6ec7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='inactivityalertcontact',
            index=models.Index(fields=['trainer', 'contacted_at'], name='alerts_inac_trainer_98db00_idx'),
        ),
        migrations.AddIndex(
            model_name='inactivityalertcontact',
            index=models.Index(fields=['alert', 'contacted_at'], name='alerts_inac_alert_i_858913_idx'),
        ),
        migrations.AddIndex(
            model_name='memberjustifiedabsence',
            index=models.Index(fields=['member', 'is_active', 'start_date', 'end_date'], name='alerts_memb_member__ef30b8_idx'),
        ),
    ]
