# Generated by Django 5.2.12 on 2026-03-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('maintenance', 'Maintenance')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommended_foods', models.TextField(blank=True)),
                ('foods_to_limit', models.TextField(blank=True)),
                ('timing_suggestions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('maintenance', 'Maintenance')], max_length=20)),
                ('calorie_range_min', models.PositiveIntegerField(default=1800)),
                ('calorie_range_max', models.PositiveIntegerField(default=2200)),
                ('protein_focus', models.CharField(blank=True, max_length=200)),
                ('carb_strategy', models.CharField(blank=True, max_length=200)),
                ('hydration_recommendation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutritionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['priority_order'],
            },
        ),
    ]
