# Generated by Django 5.2.12 on 2026-03-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionprofile',
            name='training_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to='plans.trainingplan'),
        ),
        migrations.AddField(
            model_name='plannutritionlink',
            name='guideline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='nutrition.nutritionguideline'),
        ),
        migrations.AddField(
            model_name='plannutritionlink',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_links', to='plans.trainingplan'),
        ),
        migrations.AlterUniqueTogether(
            name='plannutritionlink',
            unique_together={('plan', 'guideline')},
        ),
    ]
