# Generated by Django 5.2.12 on 2026-03-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
        ('users', '0002_memberprofile_trainer_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('maintenance', 'Maintenance')], max_length=20)),
                ('nivel_adherencia_recomendado', models.CharField(choices=[('low', 'Baja adherencia'), ('medium', 'Adherencia media'), ('high', 'Alta adherencia')], default='medium', max_length=10)),
                ('calorie_range_min', models.PositiveIntegerField(default=1800)),
                ('calorie_range_max', models.PositiveIntegerField(default=2200)),
                ('protein_focus', models.CharField(blank=True, max_length=200)),
                ('carb_strategy', models.CharField(blank=True, max_length=200)),
                ('hydration_recommendation', models.CharField(blank=True, max_length=200)),
                ('esta_activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_nutricion', to='users.trainerprofile')),
            ],
            options={
                'db_table': 'plantillas_nutricion',
                'ordering': ['nombre', 'id'],
            },
        ),
    ]
