# Generated by Django 5.2.12 on 2026-03-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='users.memberprofile'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='method_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='billing.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='users.memberprofile'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='billing.membershipplan'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='billing.paymentschedule'),
        ),
    ]
