# Generated by Django 5.2.12 on 2026-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('users', '0002_memberprofile_trainer_asignado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status', 'paid_at'], name='billing_pay_status_b1ec88_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['schedule', 'status'], name='billing_pay_schedul_09e6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['member', 'is_active', 'due_date'], name='billing_pay_member__286055_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['plan', 'is_active'], name='billing_pay_plan_id_575826_idx'),
        ),
    ]
