# Generated by Django 5.2.12 on 2026-03-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentrecord_billing_pay_status_b1ec88_idx_and_more'),
        ('users', '0003_memberprofile_users_membe_trainer_0c80c8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('recurrence_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('auto_generate_next', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-start_date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_plans', to='users.trainerprofile'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='billing.membershipplan'),
        ),
        migrations.AddIndex(
            model_name='membershipplan',
            index=models.Index(fields=['trainer', 'is_active'], name='billing_mem_trainer_30915f_idx'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.memberprofile'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.membershipplan'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='users.trainerprofile'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='billing.membersubscription'),
        ),
        migrations.AddIndex(
            model_name='membersubscription',
            index=models.Index(fields=['member', 'is_active'], name='billing_mem_member__8bb618_idx'),
        ),
        migrations.AddIndex(
            model_name='membersubscription',
            index=models.Index(fields=['trainer', 'is_active'], name='billing_mem_trainer_208d10_idx'),
        ),
        migrations.AddIndex(
            model_name='membersubscription',
            index=models.Index(fields=['plan', 'is_active'], name='billing_mem_plan_id_615aaa_idx'),
        ),
    ]
