# Generated by Django 5.2.12 on 2026-03-31 20:50

from datetime import date

from django.db import migrations


def migrar_planes_y_suscripciones(apps, schema_editor):
    MembershipPlan = apps.get_model('billing', 'MembershipPlan')
    MemberSubscription = apps.get_model('billing', 'MemberSubscription')
    PaymentSchedule = apps.get_model('billing', 'PaymentSchedule')
    PaymentRecord = apps.get_model('billing', 'PaymentRecord')
    MemberProfile = apps.get_model('users', 'MemberProfile')
    TrainerProfile = apps.get_model('users', 'TrainerProfile')

    fallback_trainer = TrainerProfile.objects.order_by('id').first()

    for plan in MembershipPlan.objects.filter(trainer__isnull=True).order_by('id'):
        trainer_id = (
            MemberProfile.objects
            .filter(membership_plan_id=plan.id, trainer_asignado__isnull=False)
            .order_by('id')
            .values_list('trainer_asignado_id', flat=True)
            .first()
        )
        if trainer_id:
            plan.trainer_id = trainer_id
            plan.save(update_fields=['trainer'])
        elif fallback_trainer:
            plan.trainer_id = fallback_trainer.id
            plan.save(update_fields=['trainer'])

    for member in MemberProfile.objects.filter(membership_plan__isnull=False).order_by('id'):
        plan = member.membership_plan
        trainer = member.trainer_asignado or plan.trainer or fallback_trainer
        if trainer is None:
            continue

        active_schedule = (
            PaymentSchedule.objects
            .filter(member_id=member.id, is_active=True)
            .order_by('-due_date', '-id')
            .first()
        )
        latest_record = (
            PaymentRecord.objects
            .filter(schedule__member_id=member.id)
            .order_by('-schedule__due_date', '-id')
            .first()
        )
        agreed_price = latest_record.amount if latest_record else plan.price_monthly
        start_date = member.join_date or date.today()
        next_billing_date = active_schedule.due_date if active_schedule else start_date
        recurrence_type = active_schedule.recurrence_type if active_schedule else 'monthly'
        grace_period_days = active_schedule.grace_period_days if active_schedule else 7
        auto_generate_next = active_schedule.auto_generate_next if active_schedule else True
        is_active = active_schedule.is_active if active_schedule else member.is_active

        subscription, created = MemberSubscription.objects.get_or_create(
            member_id=member.id,
            plan_id=plan.id,
            trainer_id=trainer.id,
            is_active=is_active,
            defaults={
                'agreed_price': agreed_price,
                'start_date': start_date,
                'next_billing_date': next_billing_date,
                'recurrence_type': recurrence_type,
                'grace_period_days': grace_period_days,
                'auto_generate_next': auto_generate_next,
            },
        )

        if not created:
            subscription.agreed_price = agreed_price
            subscription.start_date = start_date
            subscription.next_billing_date = next_billing_date
            subscription.recurrence_type = recurrence_type
            subscription.grace_period_days = grace_period_days
            subscription.auto_generate_next = auto_generate_next
            subscription.trainer_id = trainer.id
            subscription.save(
                update_fields=[
                    'agreed_price',
                    'start_date',
                    'next_billing_date',
                    'recurrence_type',
                    'grace_period_days',
                    'auto_generate_next',
                    'trainer',
                ]
            )

        PaymentSchedule.objects.filter(
            member_id=member.id,
            is_active=True,
            subscription__isnull=True,
        ).update(subscription_id=subscription.id, plan_id=plan.id)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_membersubscription_alter_membershipplan_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_planes_y_suscripciones, noop_reverse),
    ]
