# Generated by Django 5.2.12 on 2026-04-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_migrate_existing_membership_data'),
        ('users', '0004_auditlog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersubscription',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='commercial_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='receipt_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='membersubscription',
            index=models.Index(fields=['status', 'is_active'], name='billing_mem_status_cd8675_idx'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='recurrence_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='recurrence_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
