# Generated by Django 5.2.12 on 2026-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentrecord_billing_pay_status_b1ec88_idx_and_more'),
        ('users', '0002_memberprofile_trainer_asignado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['trainer_asignado', 'is_active'], name='users_membe_trainer_0c80c8_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['membership_plan', 'is_active'], name='users_membe_members_a42b16_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['join_date'], name='users_membe_join_da_700a0e_idx'),
        ),
    ]
